### ISSUE TITLE
Issue with vue version: 2.5.2 

### ISSUE THREAD

**Issue by mathieustan** [meteor-vue/vue#3]
Hello,

I think this VueJS fork should have the same version as offical vue :
--> 2.5.16

I can't setup test units with jest & vue/test-utils because I've got this error: 

```
Vue packages version mismatch:
    - vue@2.5.2
    - vue-template-compiler@2.5.16
```

Any suggestions ?

**Comment by mitar** [comment]
What do you mean? Just install `vue-template-compiler@2.5.2` and it will work for you.

Or are you saying that you need the newest Vue for some reason and this fork should be updated? This is always a problem with fork, it lags behind. :-)

**Comment by mathieustan** [comment]
last `vue-template-compiler` version is 2.5.16 (2.5.2 doesn't exist).
I managed to get official vuejs repo working on my project. So It fixed the issue.

**Comment by mitar** [comment]
Pretty sure it exists, [I am using it here](https://github.com/peer/doc/blob/master/package-lock.json#L5985).

I am glad you resolved the issue.
